### ISSUE TITLE
Add help to annotation/translation

### ISSUE THREAD

**Issue by nyborrobyn** [aikuma/aikuma-ng#115]
I am creating a translation. I messed up and want to just delete the last couple of sections. I figured out that the circle-arrow symbol will do that, but it took me a bit -- it’s not obvious. (I thought that meant ‘replay’ rather than ‘redo’.) 

(Is there a way there could be a pop-up info screen on this panel to indicate that these things will happen? This was not expected. Maybe there is and I missed it.) 

Also is there a reason that the action for deleting is ‘esc’ in annotation but ‘replay’ symbol in translation? Could these be the same?

**Comment by Lingomat** [comment]
The audio annotation interface needs some love. It doesn't have a help pop up, I'll repurpose this issue to that and take care of it shortly.

The escape key is common in both annotation and respeaking/translation. Escape doesn't have a button in the annotation UI. So the issue here is that the re-do icon isn't really a redo but is delete?

Another consistency issue: play-to-mark is left shift in respeaking/translation and it's left control in the annotation UI. I think the respeaking/translation view should change to control keys.

Open question on whether we should have buttons in the annotation UI. I've mostly operated under the assumption that keys are considerably more efficient. But the respeaking/translation view will be useful on a mobile device, and obviously one has to use screen presses there.

I also think respeaking/translation needs some tweaks to guard against mistaken short presses. Also, one can overlap key presses and currently the UI ignores the key press and the user may not pick up that recording has not begun. I think some broader improvements are necessary but these would be a good start.

Thanks Robyn, any other suggestions for behavior improvements to respeaking/translate most welcome. I'm particularly interested in whether reviewing previous audio is helpful. Steven and I found through prior testing of Aikuma on mobile that this can lead to users fussing over getting something perfect rather than carrying on and finishing.

**Comment by nyborrobyn** [comment]
Good point about inconsistency between respeaking/translation UI vs. annotation UI and having different keys. Seems like it should be uniform, because already using keys vs. buttons is a new interface for less tech-savvy people (my intuition, don't have data to back this up).

Re: your question about reviewing previous audio -- what is the scenario? I'm not sure I follow.

**Comment by Lingomat** [comment]
Say you've translated a few parts but aren't done yet. Right now there's no way to review the work you just did. You can undo the last segment, and keep doing that, but you can never hear the translation you recorded as at the moment. You can exit to the session view and press play on your work in progress translation, and then go back to translation.

I'm okay with this, because it's a compromise. You can review but we don't distract the user with fussing over producing the perfect translation. This is just based on our experience with the mobile app.
