### ISSUE TITLE
"Annotation" terminology

### ISSUE THREAD

**Issue by nyborrobyn** [aikuma/aikuma-ng#116]
Is an ‘annotation’ the best option for transcribing in the source language? A translation is obviously in another language, so what is the right thing for the source language? ("Transcription" seems more intuitive to me, since I would expect annotation to contain notes about the story, cultural context, etc.)

**Comment by Lingomat** [comment]
Yes, this has bothered me for a while. Annotation is an umbrella term for adding any additional description to an original recording, including audio annotations. Originally I think we preferred annotation for a 'transcription' because in English, at least, it seems less technical.

I agree it is confusing. Perhaps we should accept the broad definition of annotation and change the current 'annotation' type in the app to transcription. 

@stevenbird What say you?

**Comment by Lingomat** [comment]
Steven agreed so we'll make this change.
