### ISSUE TITLE
'About Aikuma NG': feedback re text

### ISSUE THREAD

**Issue by Netesten** [aikuma/aikuma-ng#26]
1. ..."is the result OF an international.."
2. "The Aikuma name Aikuma means..." : suggest change " _Aikuma_ means ..." (italicised or quotes)
3. "...the is must more to do.." :  "... there is much more to do.."
4. "...suggesting improve features...": suggest change: "... suggesting improvements.." 
5. Could the tone of this piece be more professional - comes across as a bit rough?
6. Don't understand: " Fork Aikuma ... PRs": use clearer text?
7. What does NG in Aikuma NG mean?

**Comment by Lingomat** [comment]
Good feedback. Tone wise, it should be colloquial. The reason is because we're taking a stance on the side of people who don't value such language, and it also presents translation difficulties.

Yes, it's no good putting a line of jargon for developers. We should just link GitHub.

There's quite a bit more text in the description on the store app which covers NG. A short form of this explanation could go in the about text. However I think this should avoid being a wall of text. I'd actually rather do it as a video!

**Comment by Netesten** [comment]
Video sounds great! Could include of recording of interface, for help. To
add to the on-screen help text.

**Comment by Lingomat** [comment]
Changes incorporated  in 902.
