### ISSUE TITLE
Finish button

### ISSUE THREAD

**Issue by stevenbird** [aikuma/aikuma-ng#36]
In the respeaking activity, the finish button seems to be identical to the back button. Can we get rid of the finish button?

**Comment by Lingomat** [comment]
We could. It's there to give some confidence that the work has been saved, which is not obvious otherwise (it's saved as we go)

**Comment by Lingomat** [comment]
We've adopted an accept tick instead of the rather archaic floppy disk save icon. It's use is also justified because it's consistent with all activity views (except annotation, it should probably be inserted there).

In some views the enabled/disabled status of continue is informative. Not on respeaking, but for translate and for record new. 

It also turns out that the breadcrumb nav is not obvious to everyone as a means to return to a previous view.
