### ISSUE TITLE
If stuck in "Translate", no way to cancel

### ISSUE THREAD

**Issue by hatton** [aikuma/aikuma-ng#52]
I'm having trouble in in the translation screen (will report separately), but I think all screens need an obvious way to cancel the activity. It appears that I need to save, which is cognitively difficult when one has only produced garbage :-)

**Comment by Lingomat** [comment]
Good point again. We've just assumed the user will navigate away. 

Also, we save as we go. Which is often fine but there are probably times you just want to cancel in which case we should remove work that was done. If work was done, perhaps a little pop-up confirmation confirming the loss of work.

I have concerns about a proliferation of buttons, but for now we can put this behavior in with a button until we come up with something better.

**Comment by Lingomat** [comment]
![recordnew](https://cloud.githubusercontent.com/assets/1095790/14304642/27fd2f40-fbe7-11e5-8d0a-bab06ec911a6.png)

907 improves record new and respeak/translation. We will adopt a context-sensitive cancel/delete button (instead of the delete bin) and a tick for save/accept. The context sensitive button is an indication if work has been done. It switches to the delete/bin icon when work has been done and pressing it at this stage triggers a dialog confirming that the user wishes to delete this work.

This also provides a way to delete respeaking and translations that have been previously created.
