### ISSUE TITLE
Can't complete Translation task

### ISSUE THREAD

**Issue by hatton** [aikuma/aikuma-ng#53]
When I first used the Translate task, left-shift worked.  right-shift never seemed to let me record... the whole state machine, along with the messages to do this and that and then press escape, left me confused. At some point, Windows noticed all this shift pressing and came up asking if I was trying to turn on some accessibility feature (sticky keys). I said "no". That is probably unrelated.

I then followed the direction to use the right-shift to record. I got nice visual feedback during the recording. I was then told to press left-shift to listen again, but that doesn't do anything. Neither does pressing the play button. Maybe my translation/respeaking isn't being saved?

Anyhow then it said "repeat press left-shift to listen again" but now left shift does nothing.

I note that pressing the undo button does nothing (would expect it to become disabled once everything is undone).  Similarly, the "Changed your mind?" prompt does not go away despite multiple escapes.

Windows 10, beta 0.905

**Comment by Lingomat** [comment]
Ouch. It seems like there's a hamfisted way to solve #17. You can't do any work until you type a language but there's no visual confirmation that this is the case.

We're struggling a bit with visual feedback on inputs because there's a bug in the underlying angular material which stops validation from working for initial states. What we want to happen is that these boxes have a red line under them.

**Comment by Lingomat** [comment]
Resolved in 907. A validation tip appears prompting the user to enter a language, but the user is not preventing from working. They are prevented from accepting/saving until they enter a language.
