### ISSUE TITLE
Can't listen to translation

### ISSUE THREAD

**Issue by Netesten** [aikuma/aikuma-ng#57]
When I go to recording 'How to knit' and think I might re-listen to the translation, in case I can add a note, when I press shift, the region(?) starts colouring green from just after the last sound to the end i.e. blank. When I try to do the same with 'Making bread' I also cannot, play the transpation (I click on the edit option).

**Comment by Lingomat** [comment]
Okay, so, there's a way to playback the translation right from the session view page. The page that will have Home > How to knit, at the top. If you click on the translate button, since you already made a translation, a menu will open up. One of the options there is play translation, try that. 

Ultimately, the respeaking and translation views don't let you work on sound which has already been respoken. That's why it zips forward to the last span. You're expected to work through from one end to the other. If you want to listen, you can do that on either the session view, as I mentioned, or you can go into the annotator view. This is more powerful, you can move around anywhere you like and play the sound, hear the translation and so on.

Specifically, consider this. You could make a new annotation of type comments, and join the translation track (press the button on the right of the new annotation). Then you could move to any translated bit you like and type a note for that bit. In other words, you can create several annotations for your translation, they don't have to be the same thing (e.g. comments vs. typing what was actually said).

**Comment by Netesten** [comment]
Thanks for your email explanation.

I had a look at the Home How to knit and when I select translation, the two
popup options are edit and record, not play.
[image: Inline images 1]

Thanks for clarifying re respeaking and translation being completed, do not
allow review of work that has been done.

I'll try having another tomorrow evening

How about have a You Tube clip of a few examples of how to use Aikuma and
record the steps, nice and slow (for people who are a bit new to it all).

**Comment by Lingomat** [comment]
I'm on it, but to say I'm taxed right now would be putting it mildly.

**Comment by Lingomat** [comment]
What you described: "I had a look at the Home How to knit and when I select translation, the two
popup options are edit and record, not play.", really this seems like you haven't recorded a translation. You get that this aspect of the app is talking about the audio annotations, things you recorded which describe the source? I'd dearly love to think of a better way to describe this, I've always found it problematic.

**Comment by Netesten** [comment]
this was in the old version.
had no prob in new version
