### ISSUE TITLE
"Confirm" should take user to immediately start annotation

### ISSUE THREAD

**Issue by nyborrobyn** [aikuma/aikuma-ng#97]
When starting a new annotation, “confirm” should take user to annotation screen. Instead, it saves and user must click on newly added annotation. This is not a huge problem, but is one extra click and not intuitive. 

More problematic would be when you accumulate several annotations in the same language, because it could get confusing to figure out which one was most recently

Step 1: 
![screen shot 2016-04-29 at 11 57 47](https://cloud.githubusercontent.com/assets/5350255/14926579/b466791a-0e01-11e6-9c42-401375bcd852.png)

What does happen next: 
![screen shot 2016-04-29 at 11 57 54](https://cloud.githubusercontent.com/assets/5350255/14926596/bb20b392-0e01-11e6-8e96-3b6649d643fe.png)

What should happen next: 
![screen shot 2016-04-29 at 11 58 08](https://cloud.githubusercontent.com/assets/5350255/14926603/c2b4427c-0e01-11e6-8258-de8984e7cb56.png)

**Comment by Lingomat** [comment]
Yes, agree. Particularly since you can add multiple annotations at the same time. 

Hmm, I can see some other things to fix here. The annotation preview is not supposed to do be any more than a line. Unclear why the track box is that large.

**Comment by nyborrobyn** [comment]
Yeah, interestingly the final screenshot you see came from a new annotation I had added that shouldn't have had any text in it. Maybe it's not intended, but it seemed to be showing both the first translation I did and the second one (blank, hadn't started yet). That seems to be the reason for the larger annotation screen, perhaps?

**Comment by Lingomat** [comment]
That's by design. The idea is to show you all of your annotations for a given source, but what shows up in the transcript on the right depends on whether you have the annotation turned on or off (the little switch).

The box should only be as big as needed though.

I can also see some more issues, you have your screen fairly narrow, perhaps just to take the screenshot, and most of the interface is reflowing okay but the annotation boxes aren't, there's no padding between the 'source only' button which is quite ugly. Probably a side effect of all that text appearing in the annotation preview. I'll try fix it at the same time.

Many thanks for this, very helpful.
